version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # AWS ka Java 17 version
      
  pre_build:
    commands:
      - echo "Maven version check kar rahe hain..."
      - mvn -version

  build:
    commands:
      - echo "Build process start ho raha hai..."
      - echo "Running Tests and Packaging..."
      - mvn clean package  # Ye command Test bhi karegi aur JAR bhi banayegi

  post_build:
    commands:
      - echo "Build complete successfully on `date`"

# Artifacts section batata hai ki build hone ke baad kya save karna hai
artifacts:
  files:
    - target/*.jar    # Sirf JAR file ko save karega
  discard-paths: yes  # Folder structure hata kar seedha file save karega
